### ISSUE TITLE
中文无法翻译成英文

### ISSUE THREAD

**Issue by OnlywaitY** [vacuityv/bob-plugin-vac-gptranslate#3]
如图所示，输入中文，翻译之后还是中文
<img width="400" alt="Snipaste_2023-12-18_10-55-47" src="https://github.com/vacuityv/bob-plugin-vac-gptranslate/assets/31655270/449b4658-9690-403b-ad91-a7b50144a90d">

**Comment by vacuityv** [comment]
感谢反馈，我今天中午测试下，可以提供下bob的版本吗在 2023年12月18日，10:57，OnlywaitY ***@***.***> 写道：﻿
如图所示，输入中文，翻译之后还是中文
Snipaste_2023-12-18_10-55-47.png (view on web)

**Comment by vacuityv** [comment]
@OnlywaitY  你好，我试了下未出现问题，能否提供下你使用的bob版本以及插件的设置呢

**Comment by OnlywaitY** [comment]
> @OnlywaitY 你好，我试了下未出现问题，能否提供下你使用的bob版本以及插件的设置呢

bob版本是0.10.1，插件设置是这样的
<img width="437" alt="image" src="https://github.com/vacuityv/bob-plugin-vac-gptranslate/assets/31655270/dbc8903f-8545-49d6-90c7-f438a038fa86">

**Comment by vacuityv** [comment]
@OnlywaitY  好的，感谢反馈，我等会装个0.10.1测试一下

**Comment by OnlywaitY** [comment]
> @OnlywaitY 好的，感谢反馈，我等会装个0.10.1测试一下

<img width="214" alt="image" src="https://github.com/vacuityv/bob-plugin-vac-gptranslate/assets/31655270/0875fa3b-dd00-4d2e-856e-4d14078ba741">
感觉是这个的原因，目标语言我选的是自动

**Comment by vacuityv** [comment]
@OnlywaitY  应该是，我这边自动会默认中文，我再接下来会识别到中文的时候把自动改为英文

**Comment by vacuityv** [comment]
@OnlywaitY  这个我刚刚修改了，目前如果要翻译的语言是中文选择自动可以正常翻译成英文了
