### ISSUE TITLE
通义/DeepSeek 等国产大模型 API 接口支持

### ISSUE THREAD

**Issue by hkunzhe** [vacuityv/bob-plugin-vac-gptranslate#4]
最近国产的大模型 （输入） token 降价了不少，是否有考虑支持通义/DeepSeek 等国产大模型 API 接口进行翻译，如果只是翻译成中文的话，国产这些模型不一定会比 GPT4 差。

**Comment by vacuityv** [comment]
@hkunzhe  明天看下，可能会考虑接入，主要是考虑到国产的很多人做了插件了

**Comment by hkunzhe** [comment]
> @hkunzhe 明天看下，可能会考虑接入，主要是考虑到国产的很多人做了插件了

目前只看到 Yi 和 Moonshot 的有插件

**Comment by vacuityv** [comment]
@hkunzhe  加了对阿里通义模型的支持
